export {ProductAbout} from './product-about'
export {ProductActions} from './product-actions'
export {ProductCharacteristics} from './product-characteristics'
export {ProductImage} from '../product-image'
export {ProductRating} from './product-rating'
export {ProductReviews} from './product-reviews'
export {RatingSummary} from './rating-summary'
export {ReviewFilter} from './review-filter'