import type { Metadata } from 'next';

import './globals.css';
import { CategoriesDrawer, Footer, Header } from './components';
import { Box } from '@mui/material';

export const metadata: Metadata = {
  title: 'Next-books',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html style={{ height: '100%', background: '#f0f0f0' }} lang='ru'>
      <head></head>
      <body
        style={{
          minHeight: '100%',
          display: 'flex',
          flexDirection: 'column',
          margin: 0,
          position: 'relative',
        }}
      >
        <Header />
        <Box sx={{ flexGrow: 1 }}>{children}</Box>

        <Footer />
        <CategoriesDrawer />
      </body>
    </html>
  );
}
